### ISSUE TITLE
Add CDB domain to handle tracking Apps/services

### ISSUE THREAD

**Issue by iTerminate** [AdvancedPhotonSource/ComponentDB#1571]
- [x] Create the domain and all supporting files. 
- [x] Add default list of settings for new domain. 
- [x] Update the database populate files to support the new domain. 
- [x] Add eTraveler support.
